version: "2"
output:
  formats:
    tab:
      path: stdout
      colors: false
linters:
  default: all
  disable:
    - cyclop
    - depguard
    - err113
    - exhaustive
    - exhaustruct
    - forcetypeassert
    - funlen
    - gochecknoglobals
    - godot
    - mnd
    - nilnil
    - nlreturn
    - tagliatelle
    - varnamelen
    - whitespace
    - wrapcheck
    - wsl
  settings:
    gosec:
      excludes:
        - G104
    lll:
      line-length: 160
    nestif:
      min-complexity: 7
    revive:
      enable-all-rules: true
      rules:
        - name: add-constant
          disabled: true
        - name: cognitive-complexity
          disabled: true
        - name: confusing-naming
          disabled: true
        - name: cyclomatic
          disabled: true
        - name: exported
          disabled: true
        - name: flag-parameter
          disabled: true
        - name: function-length
          disabled: true
        - name: line-length-limit
          disabled: true
        - name: max-public-structs
          disabled: true
        - name: nested-structs
          disabled: true
        - name: unhandled-error
          disabled: true
        - name: unused-receiver
          disabled: true
        - name: use-any
          disabled: true
  exclusions:
    generated: lax
    rules:
      - linters:
          - gocyclo
        path: influxdb3/query_iterator\.go,influxdb3/point_value_iterator\.go
      - linters:
          - goconst
          - paralleltest
          - tagalign
          - testableexamples
          - testpackage
          - thelper
          - tparallel
          - unparam
        path: _test\.go
      - path: _test\.go
        text: Error return value of .((os.)?std(out|err)..*|.*Close.*|.*Flush|.*Disconnect|.*Clear|os.Remove(All)?|.*print(f|ln)?|os.(Un)?Setenv). is not checked
      - path: _test\.go
        text: 'G404: Use of weak random number generator'
      - path: _test\.go
        text: 'unused-parameter:'
      - path: _test\.go
        text: 'require-error:'
      - path: _test\.go
        text: 'go-require:'
      - path: .*example(_.*)?_test\.go$
        text: 'exitAfterDefer:'
      - path: .*example(_.*)?_test\.go$
        text: 'deep-exit:'
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gci
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
      - _test\.go
